services:
  db:
    image: ghcr.io/openimis/openimis-mssql:${DB_TAG:-latest}
    init: true
    restart: always
    environment:
      - DB_USER_PASSWORD=${DB_PASSWORD}
      - SA_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - ACCEPT_EULA=${ACCEPT_EULA}
      - DEMO_DATASET=${DEMO_DATASET}
      - DB_ENGINE=mssql
    healthcheck:
      test: "bash /app/healthcheck.sh"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 100s
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    networks:
      openimis-net:
    volumes:
      - database:/var/opt/mssql/data
    ports:
      - 1433:1433
  ## WARNING:
    ## exposing the database port outside the openimis-net network
    ## may lead to security issue (depending on your network topology)
